Bug #51739 uvmm-node: Fix initial install
> univention-virtual-machine-manager-node-common (7.0.1-7A~4.4.0.202007291719) wird eingerichtet ...
> Module: uvmm_restore
> 'NoneType' object has no attribute 'endswith'

This is causes by the code doing `os.path.join(None, "...")`, which
internally does a `None.endswith("...")`, which raises `AttributeError()`.

Luckily `univention.config_registry.handler:run_module()` catches that
exception and prints the error:

> except (AttributeError, ImportError) as ex:
>     print(ex, file=sys.stderr)

But we should handle that case anyway.